### ISSUE TITLE
Login Panel is not working

### ISSUE THREAD

**Issue by arpanaditya** [sawolabs/html-example#2]
The login panel is not working.
![sawolabs](https://user-images.githubusercontent.com/75975428/152299394-878ec601-7319-4358-a141-e32d0bef5f16.png)

**Comment by KSwarna99** [comment]
@arpanaditya This can occur due to an invalid hostname and/or api key. If the hostname 'localhost' is not rendering the login form, change it to 127.0.0.1 on the client dashboard. Refer to this [here](https://docs.sawolabs.com/sawo/faqs)
